import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class EditPage extends StatefulWidget {
  static String routeName = '/pages/edit_page';
  EditPage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<EditPage> {

  var listItem = ['one', 'two', 'three'];
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('App Name'),
      ),
      body: ListView(
        children: [
          ListTile(title: Text('利尻岳')),
          ListTile(title: Text('羅臼岳')),
          ListTile(title: Text('斜里岳')),
          ListTile(title: Text('阿寒岳')),
          ListTile(title: Text('大雪山')),
          ListTile(title: Text('トムラウシ山')),
          ListTile(title: Text('十勝岳')),
          ListTile(title: Text('幌尻岳')),
          ListTile(title: Text('後方羊蹄山')),
          ListTile(title: Text('東北')),
          ListTile(title: Text('岩木山')),
          ListTile(title: Text('八甲田山')),
          ListTile(title: Text('八幡平')),
          ListTile(title: Text('岩手山')),
          ListTile(title: Text('早池峰山')),
          ListTile(title: Text('鳥海山')),
          ListTile(title: Text('月山')),
          ListTile(title: Text('朝日連峰')),
          ListTile(title: Text('蔵王山')),
          ListTile(title: Text('飯豊連邦')),
          ListTile(title: Text('吾妻山')),
          ListTile(title: Text('安達太良山')),
          ListTile(title: Text('盤梯山')),
          ListTile(title: Text('会津駒ケ岳')),
          ListTile(title: Text('北関東・尾瀬・日光')),
          ListTile(title: Text('那須岳')),
          ListTile(title: Text('筑波山')),
          ListTile(title: Text('燧ヶ岳')),
          ListTile(title: Text('至仏山')),
          ListTile(title: Text('武尊山')),
          ListTile(title: Text('赤城山')),
          ListTile(title: Text('男体山')),
          ListTile(title: Text('日光白根山')),
          ListTile(title: Text('皇海山')),
          ListTile(title: Text('上信越')),
          ListTile(title: Text('越後駒ヶ岳')),
          ListTile(title: Text('平ヶ岳')),
          ListTile(title: Text('巻機山')),
          ListTile(title: Text('谷川岳')),
          ListTile(title: Text('苗場山')),
          ListTile(title: Text('雨飾山')),
          ListTile(title: Text('妙高山')),
          ListTile(title: Text('火打山')),
          ListTile(title: Text('高妻山')),
          ListTile(title: Text('草津白根山')),
          ListTile(title: Text('四阿山')),
          ListTile(title: Text('浅間山')),
          ListTile(title: Text('秩父・多摩・南関東')),
          ListTile(title: Text('両神山')),
          ListTile(title: Text('甲武信岳')),
          ListTile(title: Text('金峰山')),
          ListTile(title: Text('瑞牆山')),
          ListTile(title: Text('雲取山')),
          ListTile(title: Text('大菩薩嶺')),
          ListTile(title: Text('丹沢')),
          ListTile(title: Text('富士山')),
          ListTile(title: Text('天城山')),
          ListTile(title: Text('北アルプス')),
          ListTile(title: Text('白馬岳')),
          ListTile(title: Text('五竜岳')),
          ListTile(title: Text('鹿島槍ヶ岳')),
          ListTile(title: Text('剱岳')),
          ListTile(title: Text('立山')),
          ListTile(title: Text('薬師岳')),
          ListTile(title: Text('黒部五郎岳')),
          ListTile(title: Text('水晶岳')),
          ListTile(title: Text('鷲羽岳')),
          ListTile(title: Text('槍ヶ岳')),
          ListTile(title: Text('穂高岳')),
          ListTile(title: Text('常念岳')),
          ListTile(title: Text('笠ヶ岳')),
          ListTile(title: Text('焼岳')),
          ListTile(title: Text('乗鞍岳')),
          ListTile(title: Text('美ヶ原・八ヶ岳・中央アルプス')),
          ListTile(title: Text('美ヶ原')),
          ListTile(title: Text('霧ヶ峰')),
          ListTile(title: Text('蓼科山')),
          ListTile(title: Text('八ヶ岳')),
          ListTile(title: Text('御嶽山')),
          ListTile(title: Text('木曽駒ヶ岳')),
          ListTile(title: Text('空木岳')),
          ListTile(title: Text('恵那山')),
          ListTile(title: Text('南アルプス')),
          ListTile(title: Text('甲斐駒ヶ岳')),
          ListTile(title: Text('仙丈ヶ岳')),
          ListTile(title: Text('鳳凰山')),
          ListTile(title: Text('北岳')),
          ListTile(title: Text('間ノ岳')),
          ListTile(title: Text('塩見岳')),
          ListTile(title: Text('悪沢岳')),
          ListTile(title: Text('赤石岳')),
          ListTile(title: Text('聖岳')),
          ListTile(title: Text('光岳')),
          ListTile(title: Text('北陸・近畿・中国・四国')),
          ListTile(title: Text('白山')),
          ListTile(title: Text('荒島岳')),
          ListTile(title: Text('伊吹山')),
          ListTile(title: Text('大台ヶ原山')),
          ListTile(title: Text('大峰山')),
          ListTile(title: Text('大山')),
          ListTile(title: Text('剣山')),
          ListTile(title: Text('石鎚山')),
          ListTile(title: Text('九州')),
          ListTile(title: Text('九重山')),
          ListTile(title: Text('祖母山')),
          ListTile(title: Text('阿蘇山')),
          ListTile(title: Text('霧島山')),
          ListTile(title: Text('開聞岳')),
          ListTile(title: Text('宮之浦岳')),
         
        ],
      ),
    );
  }
}

