import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class EditPage extends StatefulWidget {
  static String routeName = '/pages/edit_page';
  EditPage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<EditPage> {

  var listItem = ['one', 'two', 'three'];
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('App Name'),
      ),
      body: ListView(
        children: [
          ListTile(title: Text('北海道')),
          ListTile(title: Text('天塩岳')),
          ListTile(title: Text('石狩岳')),
          ListTile(title: Text('ニペソツ山')),
          ListTile(title: Text('カムイエクウチカウシ山')),
          ListTile(title: Text('ペテガリ岳')),
          ListTile(title: Text('芦別岳')),
          ListTile(title: Text('夕張岳')),
          ListTile(title: Text('暑寒別岳')),
          ListTile(title: Text('樽前山')),
          ListTile(title: Text('北海道駒ヶ岳')),
          ListTile(title: Text('東北')),
          ListTile(title: Text('白神岳 ')),
          ListTile(title: Text('姫神山 ')),
          ListTile(title: Text('秋田駒ヶ岳 ')),
          ListTile(title: Text('和賀岳 ')),
          ListTile(title: Text('森吉山 ')),
          ListTile(title: Text('焼石岳 ')),
          ListTile(title: Text('栗駒山 ')),
          ListTile(title: Text('神室山 ')),
          ListTile(title: Text('船形山 ')),
          ListTile(title: Text('以東岳')),
          ListTile(title: Text('杁差岳 ')),
          ListTile(title: Text('二王子岳 ')),
          ListTile(title: Text('帝釈山 ')),
          ListTile(title: Text('会津朝日岳 ')),
          ListTile(title: Text('関東')),
          ListTile(title: Text('女峰山')),
          ListTile(title: Text('仙ノ倉山 ')),
          ListTile(title: Text('榛名山 ')),
          ListTile(title: Text('浅間隠山 ')),
          ListTile(title: Text('妙義山')),
          ListTile(title: Text('荒船山 ')),
          ListTile(title: Text('武甲山 ')),
          ListTile(title: Text('白石山')),
          ListTile(title: Text('大岳山')),
          ListTile(title: Text('甲信越')),
          ListTile(title: Text('御神楽岳 ')),
          ListTile(title: Text('守門岳')),
          ListTile(title: Text('荒沢岳')),
          ListTile(title: Text('八海山')),
          ListTile(title: Text('中ノ岳 ')),
          ListTile(title: Text('佐武流山')),
          ListTile(title: Text('白砂山 ')),
          ListTile(title: Text('鳥甲山')),
          ListTile(title: Text('岩菅山')),
          ListTile(title: Text('飯縄山 ')),
          ListTile(title: Text('黒姫山 ')),
          ListTile(title: Text('戸隠山 ')),
          ListTile(title: Text('天狗岳')),
          ListTile(title: Text('御座山')),
          ListTile(title: Text('乾徳山')),
          ListTile(title: Text('茅ヶ岳 ')),
          ListTile(title: Text('御正体山')),
          ListTile(title: Text('三ツ峠山')),
          ListTile(title: Text('毛無山')),
          ListTile(title: Text('櫛形山')),
          ListTile(title: Text('七面山')),
          ListTile(title: Text('北・中央アルプス')),
          ListTile(title: Text('雪倉岳')),
          ListTile(title: Text('針ノ木岳')),
          ListTile(title: Text('毛勝山')),
          ListTile(title: Text('奥大日岳')),
          ListTile(title: Text('烏帽子岳')),
          ListTile(title: Text('赤牛岳')),
          ListTile(title: Text('餓鬼岳')),
          ListTile(title: Text('有明山')),
          ListTile(title: Text('燕岳')),
          ListTile(title: Text('大天井岳')),
          ListTile(title: Text('霞沢岳')),
          ListTile(title: Text('経ヶ岳')),
          ListTile(title: Text('南駒ヶ岳')),
          ListTile(title: Text('安平路山')),
          ListTile(title: Text('小秀山')),
          ListTile(title: Text('南アルプス')),
          ListTile(title: Text('鋸岳')),
          ListTile(title: Text('農鳥岳')),
          ListTile(title: Text('笊ヶ岳')),
          ListTile(title: Text('上河内岳')),
          ListTile(title: Text('池口岳')),
          ListTile(title: Text('大無間山')),
          ListTile(title: Text('東海・北陸')),
          ListTile(title: Text('愛鷹山')),
          ListTile(title: Text('金剛堂山 ')),
          ListTile(title: Text('位山')),
          ListTile(title: Text('笈ヶ岳')),
          ListTile(title: Text('大日ヶ岳')),
          ListTile(title: Text('能郷白山')),
          ListTile(title: Text('近畿')),
          ListTile(title: Text('御在所岳')),
          ListTile(title: Text('釈迦ヶ岳')),
          ListTile(title: Text('伯母子岳')),
          ListTile(title: Text('金剛山')),
          ListTile(title: Text('武奈ヶ岳')),
          ListTile(title: Text('四国・中国')),
          ListTile(title: Text('氷ノ山')),
          ListTile(title: Text('上蒜山 ')),
          ListTile(title: Text('三瓶山')),
          ListTile(title: Text('三嶺')),
          ListTile(title: Text('東赤石山 ')),
          ListTile(title: Text('笹ヶ峰 ')),
          ListTile(title: Text('九州')),
          ListTile(title: Text('英彦山')),
          ListTile(title: Text('由布岳')),
          ListTile(title: Text('大崩山 ')),
          ListTile(title: Text('雲仙岳')),
          ListTile(title: Text('市房山')),
          ListTile(title: Text('尾鈴山')),
          ListTile(title: Text('高千穂峰 ')),
          ListTile(title: Text('桜島')),

        ],
      ),
    );
  }
}
